{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    {{- include "blog-app-api.labels" . | nindent 4 }}
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
    # meta.helm.sh/release-name:  "{{ .Release.Name }}"
    # meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
automountServiceAccountToken: {{ .Values.serviceAccount.automount | default true }}
{{- end }}