# Use the .NET 6 runtime as a base image
FROM mcr.microsoft.com/dotnet/runtime:8.0

# Set the working directory to /app
WORKDIR /app

# Copy the contents of the published app to the container's /app directory
COPY bin/Release/net8.0/publish/ .

# Expose port 80 to the outside world
EXPOSE 80

# Set the command to run when the container starts
CMD ["dotnet", "BlogApp.dll"]