replicaCount: 1

image:
  repository: blogappacr.azurecr.io/blog-app-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: blog-api.local
      paths:
        - path: /
          pathType: Prefix
  # tls: []
  # Example:
  # tls:
  #   - secretName: chart-example-tls
  #     hosts:
  #       - chart-example.local

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

nodeSelector: {}
tolerations: []
affinity: {}

serviceAccount:
  create: true
  name: "blog-app-api-sa" # Use a different name
  annotations: {}
  automount: true
  
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80